// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import "github.com/astaxie/beego/orm"

type NewProduct struct {
	Name  string `json:"name"`
	Price string `json:"price"`
}

type Product struct {
	Id    int    `orm:"auto"`
	Name  string `json:"name"`
	Price string `json:"price"`
}

func init() {
	orm.RegisterModel(new(Product))
}
